[package]
name = "Violent-Rust-sniffer"
version = "0.1.0"
authors = ["Max Kelly <kellymr1@rose-hulman.edu>"]
edition = "2018"

[dependencies]
# zip = "0.5"  for when running the unzipper
getopts = "0.2.18"
pnet = "0.21.0"
lib_blaster = "0.3.1"
synner = "0.1.1"